<a href="https://colab.research.google.com/github/DebdasPaul/Tensorflow_masterclass_udemy/blob/main/00_tensorflow_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamental concepts of tensorflow

More specifically, we are going to cover

* introduction to tensors
* Getting information from tensors
* Manipulating tensors
* tensors & Numpy
* Using @tf.function (a way to speed up python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises


# Introduction to Tensors

In [2]:
# Import Tensorflow

import tensorflow as tf
print (tf.__version__)

2.15.0


In [3]:
# Create tensors with tf.constant

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of diemsnions

scaler.ndim

0

In [5]:
# create and vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# check the dimension
vector.ndim

1

In [9]:
# Create a matrix

matrix = tf.constant ([[10,10],[3,2]])
matrix.ndim

2

In [16]:
# create another matrix, dtype related to space

another_matrix = tf.constant ([[10.,10.],[3.,2.],[12.,10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 3.,  2.],
       [12., 10.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [14]:
tensor = tf.constant([[[1,2,3], [4,5,6]], [[2,3,4], [8,9,10]], [[3,4,5],[5,6,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 2,  3,  4],
        [ 8,  9, 10]],

       [[ 3,  4,  5],
        [ 5,  6,  7]]], dtype=int32)>

In [15]:
tensor.ndim

3

In [ ]:
What we have created so far
* scaler: single number
* vector: a number with direction (wind speed and direction)
* matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scaler, a 1-dimensional tensor is a vector)